version: "3.1"

services:

  node:
    build: .
    container_name: node
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "012345"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
